source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
use_frameworks!

target 'MayTheForceBeWith_JeffersonSB' do
  use_frameworks!
  pod 'Moya', '~> 13.0'
  pod 'SnapKit', '~> 4.0'

  target 'MayTheForceBeWith_JeffersonSBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MayTheForceBeWith_JeffersonSBUITests' do
    # Pods for testing
  end

end
